spring:
  application:
    name: eslasticsearch
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elasticsearch?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: "123456"
#    ????
logging:
  level:
    com.example: debug
mybatis-plus:
  type-aliases-package: com.study.pojo # ?????
  #mapper-locations: classpath*:/mapper/*.xml # mapper?xml????
  global-config:
    db-config:
      id-type: auto # ?????????????
      update-strategy: not_null  # ????????null??
      insert-strategy: not_null  # ????????null??
#  configuration:
#    map-underscore-to-camel-case: false



